"""Curated, cross-field reference entries for the synthetic benchmark.

Ground truth here is exact by construction: these fields are what we feed into the
.bib source and the LaTeX/biblatex renderer, so whatever PDF text comes out was
authored directly from this data - no Crossref/OpenAlex subset-coverage problem like
the real-PDF benchmark has (see docs/project-plan.md, parsing_match.py docstring).

`broad_field` groups entries into the four field/style pairings this project targets
(one style build per field, see latex_builder.STYLE_PREAMBLES), with 30 entries per
broad field to cover a range relevant to Uni Marburg's faculties, not just the
psychology-heavy Kloft manuscripts used in the real-PDF benchmark:
- "social_behavioral" (psychology, sociology, education) -> APA7
- "humanities_theology" -> Chicago author-date
- "medicine_life_sciences" -> Vancouver
- "cs_engineering" -> IEEE
A few entries (physics) don't fit any of the four target fields and are tagged
"other" - bonus diversity, not counted toward the 10-20-per-field target.

These were sourced from memory of well-known, real published works rather than a live
Zotero pull (Zotero wasn't running when this was built - connection refused, same
issue seen earlier in this project's session). Exact bibliographic details (DOI,
volume, pages) are not independently re-verified against a live source; that doesn't
affect this benchmark's validity since the rendered PDF's ground truth is definitionally
whatever is written here, but treat these DOIs as illustrative rather than confirmed
if you need them to be independently correct for some other purpose.
"""

from dataclasses import dataclass


@dataclass
class Author:
    given: str
    family: str

    def bibtex_name(self) -> str:
        return f"{self.family}, {self.given}"


@dataclass
class SynthReferenceEntry:
    key: str
    entry_type: str  # "article", "book", "incollection", "inproceedings", "misc"
    authors: list[Author]
    year: str
    title: str
    broad_field: str = "other"
    doi: str | None = None
    journal: str | None = None
    volume: str | None = None
    number: str | None = None
    pages: str | None = None
    publisher: str | None = None
    booktitle: str | None = None
    address: str | None = None
    url: str | None = None
    note: str | None = None
    field_of_study: str = ""


_SOCIAL_BEHAVIORAL: list[SynthReferenceEntry] = [
    SynthReferenceEntry(
        key="kahneman1979prospect",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Daniel", "Kahneman"), Author("Amos", "Tversky")],
        year="1979",
        title="Prospect theory: An analysis of decision under risk",
        journal="Econometrica",
        volume="47",
        number="2",
        pages="263--291",
        doi="10.2307/1914185",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="lord1968statistical",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Frederic M.", "Lord"), Author("Melvin R.", "Novick")],
        year="1968",
        title="Statistical theories of mental test scores",
        publisher="Addison-Wesley",
        address="Reading, MA",
        field_of_study="psychometrics",
    ),
    SynthReferenceEntry(
        key="bandura1977selfefficacy",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Albert", "Bandura")],
        year="1977",
        title="Self-efficacy: Toward a unifying theory of behavioral change",
        journal="Psychological Review",
        volume="84",
        number="2",
        pages="191--215",
        doi="10.1037/0033-295X.84.2.191",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="milgram1963behavioral",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Stanley", "Milgram")],
        year="1963",
        title="Behavioral study of obedience",
        journal="Journal of Abnormal and Social Psychology",
        volume="67",
        number="4",
        pages="371--378",
        doi="10.1037/h0040525",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="festinger1957cognitive",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Leon", "Festinger")],
        year="1957",
        title="A Theory of Cognitive Dissonance",
        publisher="Stanford University Press",
        address="Stanford, CA",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="ainsworth1978patterns",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[
            Author("Mary D. Salter", "Ainsworth"), Author("Mary C.", "Blehar"),
            Author("Everett", "Waters"), Author("Sally", "Wall"),
        ],
        year="1978",
        title="Patterns of Attachment: A Psychological Study of the Strange Situation",
        publisher="Lawrence Erlbaum Associates",
        address="Hillsdale, NJ",
        field_of_study="developmental psychology",
    ),
    SynthReferenceEntry(
        key="deciryan2000what",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Edward L.", "Deci"), Author("Richard M.", "Ryan")],
        year="2000",
        title='The "what" and "why" of goal pursuits: Human needs and the self-determination of behavior',
        journal="Psychological Inquiry",
        volume="11",
        number="4",
        pages="227--268",
        doi="10.1207/S15327965PLI1104_01",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="cronbach1951coefficient",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Lee J.", "Cronbach")],
        year="1951",
        title="Coefficient alpha and the internal structure of tests",
        journal="Psychometrika",
        volume="16",
        number="3",
        pages="297--334",
        doi="10.1007/BF02310555",
        field_of_study="psychometrics",
    ),
    SynthReferenceEntry(
        key="granovetter1973strength",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Mark S.", "Granovetter")],
        year="1973",
        title="The strength of weak ties",
        journal="American Journal of Sociology",
        volume="78",
        number="6",
        pages="1360--1380",
        doi="10.1086/225469",
        field_of_study="sociology",
    ),
    SynthReferenceEntry(
        key="rosenthaljacobson1968pygmalion",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Robert", "Rosenthal"), Author("Lenore", "Jacobson")],
        year="1968",
        title="Pygmalion in the Classroom: Teacher Expectation and Pupils' Intellectual Development",
        publisher="Holt, Rinehart & Winston",
        address="New York, NY",
        field_of_study="education",
    ),
    SynthReferenceEntry(
        key="asch1956studies",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Solomon E.", "Asch")],
        year="1956",
        title="Studies of independence and conformity: I. A minority of one against a unanimous majority",
        journal="Psychological Monographs: General and Applied",
        volume="70",
        number="9",
        pages="1--70",
        doi="10.1037/h0093718",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="rosenberg1965society",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Morris", "Rosenberg")],
        year="1965",
        title="Society and the Adolescent Self-Image",
        publisher="Princeton University Press",
        address="Princeton, NJ",
        field_of_study="sociology",
    ),
    SynthReferenceEntry(
        key="rotter1966generalized",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Julian B.", "Rotter")],
        year="1966",
        title="Generalized expectancies for internal versus external control of reinforcement",
        journal="Psychological Monographs: General and Applied",
        volume="80",
        number="1",
        pages="1--28",
        doi="10.1037/h0092976",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="ekmanfriesen1971constants",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Paul", "Ekman"), Author("Wallace V.", "Friesen")],
        year="1971",
        title="Constants across cultures in the face and emotion",
        journal="Journal of Personality and Social Psychology",
        volume="17",
        number="2",
        pages="124--129",
        doi="10.1037/h0030377",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="baumeisterleary1995need",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Roy F.", "Baumeister"), Author("Mark R.", "Leary")],
        year="1995",
        title="The need to belong: Desire for interpersonal attachments as a fundamental human motivation",
        journal="Psychological Bulletin",
        volume="117",
        number="3",
        pages="497--529",
        doi="10.1037/0033-2909.117.3.497",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="bowlby1969attachment",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("John", "Bowlby")],
        year="1969",
        title="Attachment and Loss, Volume 1: Attachment",
        publisher="Basic Books",
        address="New York, NY",
        field_of_study="developmental psychology",
    ),
    SynthReferenceEntry(
        key="piaget1952origins",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Jean", "Piaget")],
        year="1952",
        title="The Origins of Intelligence in Children",
        publisher="International Universities Press",
        address="New York, NY",
        field_of_study="developmental psychology",
    ),
    SynthReferenceEntry(
        key="vygotsky1978mind",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Lev S.", "Vygotsky")],
        year="1978",
        title="Mind in Society: The Development of Higher Psychological Processes",
        publisher="Harvard University Press",
        address="Cambridge, MA",
        field_of_study="developmental psychology",
    ),
    SynthReferenceEntry(
        key="sherif1936psychology",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Muzafer", "Sherif")],
        year="1936",
        title="The Psychology of Social Norms",
        publisher="Harper & Brothers",
        address="New York, NY",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="bem1972selfperception",
        entry_type="incollection",
        broad_field="social_behavioral",
        authors=[Author("Daryl J.", "Bem")],
        year="1972",
        title="Self-perception theory",
        booktitle="Advances in Experimental Social Psychology",
        volume="6",
        pages="1--62",
        publisher="Academic Press",
        doi="10.1016/S0065-2601(08)60024-6",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="schwartz1992universals",
        entry_type="incollection",
        broad_field="social_behavioral",
        authors=[Author("Shalom H.", "Schwartz")],
        year="1992",
        title="Universals in the content and structure of values: Theoretical advances and empirical tests in 20 countries",
        booktitle="Advances in Experimental Social Psychology",
        volume="25",
        pages="1--65",
        publisher="Academic Press",
        doi="10.1016/S0065-2601(08)60281-6",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="durkheim1951suicide",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Émile", "Durkheim")],
        year="1951",
        title="Suicide: A Study in Sociology",
        publisher="Free Press",
        address="Glencoe, IL",
        note="Original work published 1897",
        field_of_study="sociology",
    ),
    SynthReferenceEntry(
        key="weber1930protestant",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Max", "Weber")],
        year="1930",
        title="The Protestant Ethic and the Spirit of Capitalism",
        publisher="Allen & Unwin",
        address="London",
        note="Original work published 1905",
        field_of_study="sociology",
    ),
    SynthReferenceEntry(
        key="becker1968crime",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Gary S.", "Becker")],
        year="1968",
        title="Crime and punishment: An economic approach",
        journal="Journal of Political Economy",
        volume="76",
        number="2",
        pages="169--217",
        doi="10.1086/259394",
        field_of_study="economics",
    ),
    SynthReferenceEntry(
        key="thalersunstein2008nudge",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Richard H.", "Thaler"), Author("Cass R.", "Sunstein")],
        year="2008",
        title="Nudge: Improving Decisions About Health, Wealth, and Happiness",
        publisher="Yale University Press",
        address="New Haven, CT",
        field_of_study="behavioral economics",
    ),
    SynthReferenceEntry(
        key="ariely2008predictably",
        entry_type="book",
        broad_field="social_behavioral",
        authors=[Author("Dan", "Ariely")],
        year="2008",
        title="Predictably Irrational: The Hidden Forces That Shape Our Decisions",
        publisher="HarperCollins",
        address="New York, NY",
        field_of_study="behavioral economics",
    ),
    SynthReferenceEntry(
        key="diener1984subjective",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Ed", "Diener")],
        year="1984",
        title="Subjective well-being",
        journal="Psychological Bulletin",
        volume="95",
        number="3",
        pages="542--575",
        doi="10.1037/0033-2909.95.3.542",
        field_of_study="psychology",
    ),
    SynthReferenceEntry(
        key="ross1977intuitive",
        entry_type="incollection",
        broad_field="social_behavioral",
        authors=[Author("Lee", "Ross")],
        year="1977",
        title="The intuitive psychologist and his shortcomings: Distortions in the attribution process",
        booktitle="Advances in Experimental Social Psychology",
        volume="10",
        pages="173--220",
        publisher="Academic Press",
        doi="10.1016/S0065-2601(08)60357-3",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="tajfelturner1979integrative",
        entry_type="incollection",
        broad_field="social_behavioral",
        authors=[Author("Henri", "Tajfel"), Author("John C.", "Turner")],
        year="1979",
        title="An integrative theory of intergroup conflict",
        booktitle="The Social Psychology of Intergroup Relations",
        publisher="Brooks/Cole",
        address="Monterey, CA",
        pages="33--47",
        field_of_study="social psychology",
    ),
    SynthReferenceEntry(
        key="markuskitayama1991culture",
        entry_type="article",
        broad_field="social_behavioral",
        authors=[Author("Hazel Rose", "Markus"), Author("Shinobu", "Kitayama")],
        year="1991",
        title="Culture and the self: Implications for cognition, emotion, and motivation",
        journal="Psychological Review",
        volume="98",
        number="2",
        pages="224--253",
        doi="10.1037/0033-295X.98.2.224",
        field_of_study="cultural psychology",
    ),
]

_HUMANITIES_THEOLOGY: list[SynthReferenceEntry] = [
    SynthReferenceEntry(
        key="foucault1977discipline",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Michel", "Foucault")],
        year="1977",
        title="Discipline and Punish: The Birth of the Prison",
        publisher="Vintage Books",
        address="New York, NY",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="kuhn1962structure",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Thomas S.", "Kuhn")],
        year="1962",
        title="The Structure of Scientific Revolutions",
        publisher="University of Chicago Press",
        address="Chicago, IL",
        field_of_study="history and philosophy of science",
    ),
    SynthReferenceEntry(
        key="said1978orientalism",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Edward W.", "Said")],
        year="1978",
        title="Orientalism",
        publisher="Pantheon Books",
        address="New York, NY",
        field_of_study="literary criticism",
    ),
    SynthReferenceEntry(
        key="barth1956churchdogmatics",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Karl", "Barth")],
        year="1956",
        # Church Dogmatics is a 13-part-volume work published 1932-1967; citing it as
        # one undated monolith (the original entry here) doesn't correspond to any
        # real single publication, so this cites the specific volume instead.
        title="Church Dogmatics, Volume IV.1: The Doctrine of Reconciliation",
        publisher="T&T Clark",
        address="Edinburgh",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="gadamer1975truth",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Hans-Georg", "Gadamer")],
        year="1975",
        title="Truth and Method",
        publisher="Continuum",
        address="London",
        field_of_study="philosophical hermeneutics",
    ),
    SynthReferenceEntry(
        key="arendt1958human",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Hannah", "Arendt")],
        year="1958",
        title="The Human Condition",
        publisher="University of Chicago Press",
        address="Chicago, IL",
        field_of_study="political philosophy",
    ),
    SynthReferenceEntry(
        key="derrida1976grammatology",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Jacques", "Derrida")],
        year="1976",
        title="Of Grammatology",
        publisher="Johns Hopkins University Press",
        address="Baltimore, MD",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="eliade1959sacred",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Mircea", "Eliade")],
        year="1959",
        title="The Sacred and the Profane: The Nature of Religion",
        publisher="Harcourt, Brace & World",
        address="New York, NY",
        field_of_study="religious studies",
    ),
    SynthReferenceEntry(
        key="ricoeur1969symbolism",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Paul", "Ricoeur")],
        year="1969",
        title="The Symbolism of Evil",
        publisher="Beacon Press",
        address="Boston, MA",
        field_of_study="philosophy of religion",
    ),
    SynthReferenceEntry(
        key="bloom1973anxiety",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Harold", "Bloom")],
        year="1973",
        title="The Anxiety of Influence: A Theory of Poetry",
        publisher="Oxford University Press",
        address="New York, NY",
        field_of_study="literary theory",
    ),
    SynthReferenceEntry(
        key="augustine1961confessions",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("", "Augustine")],
        year="1961",
        title="Confessions",
        publisher="Penguin Classics",
        address="London",
        note="Written c. 397-400",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="nietzsche1967genealogy",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Friedrich", "Nietzsche")],
        year="1967",
        title="On the Genealogy of Morals",
        publisher="Vintage Books",
        address="New York, NY",
        note="Original work published 1887",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="heidegger1962being",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Martin", "Heidegger")],
        year="1962",
        title="Being and Time",
        publisher="Harper & Row",
        address="New York, NY",
        note="Original work published 1927",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="habermas1984theory",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Jürgen", "Habermas")],
        year="1984",
        title="The Theory of Communicative Action, Volume 1: Reason and the Rationalization of Society",
        publisher="Beacon Press",
        address="Boston, MA",
        note="Original work published 1981",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="bultmann1958jesus",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Rudolf", "Bultmann")],
        year="1958",
        title="Jesus Christ and Mythology",
        publisher="Charles Scribner's Sons",
        address="New York, NY",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="tillich1951systematic",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Paul", "Tillich")],
        year="1951",
        title="Systematic Theology, Volume 1",
        publisher="University of Chicago Press",
        address="Chicago, IL",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="niebuhr1932moral",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Reinhold", "Niebuhr")],
        year="1932",
        title="Moral Man and Immoral Society: A Study in Ethics and Politics",
        publisher="Charles Scribner's Sons",
        address="New York, NY",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="buber1970iandthou",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Martin", "Buber")],
        year="1970",
        title="I and Thou",
        publisher="Charles Scribner's Sons",
        address="New York, NY",
        note="Original work published 1923",
        field_of_study="philosophy of religion",
    ),
    SynthReferenceEntry(
        key="levinas1969totality",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Emmanuel", "Levinas")],
        year="1969",
        title="Totality and Infinity: An Essay on Exteriority",
        publisher="Duquesne University Press",
        address="Pittsburgh, PA",
        note="Original work published 1961",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="ricoeur1970freud",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Paul", "Ricoeur")],
        year="1970",
        title="Freud and Philosophy: An Essay on Interpretation",
        publisher="Yale University Press",
        address="New Haven, CT",
        note="Original work published 1965",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="white1973metahistory",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Hayden", "White")],
        year="1973",
        title="Metahistory: The Historical Imagination in Nineteenth-Century Europe",
        publisher="Johns Hopkins University Press",
        address="Baltimore, MD",
        field_of_study="history",
    ),
    SynthReferenceEntry(
        key="benjamin1968workofart",
        entry_type="incollection",
        broad_field="humanities_theology",
        authors=[Author("Walter", "Benjamin")],
        year="1968",
        title="The work of art in the age of mechanical reproduction",
        booktitle="Illuminations",
        publisher="Schocken Books",
        address="New York, NY",
        note="Original work published 1936",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="adornohorkheimer2002dialectic",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Theodor W.", "Adorno"), Author("Max", "Horkheimer")],
        year="2002",
        title="Dialectic of Enlightenment: Philosophical Fragments",
        publisher="Stanford University Press",
        address="Stanford, CA",
        note="Original work published 1944",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="butler1990gender",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Judith", "Butler")],
        year="1990",
        title="Gender Trouble: Feminism and the Subversion of Identity",
        publisher="Routledge",
        address="New York, NY",
        field_of_study="gender studies",
    ),
    SynthReferenceEntry(
        key="debeauvoir2011secondsex",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Simone", "de Beauvoir")],
        year="2011",
        title="The Second Sex",
        publisher="Vintage Books",
        address="New York, NY",
        note="Original work published 1949",
        field_of_study="philosophy",
    ),
    SynthReferenceEntry(
        key="barthes1977deathauthor",
        entry_type="incollection",
        broad_field="humanities_theology",
        authors=[Author("Roland", "Barthes")],
        year="1977",
        title="The death of the author",
        booktitle="Image-Music-Text",
        publisher="Fontana Press",
        address="London",
        note="Original essay published 1967",
        field_of_study="literary theory",
    ),
    SynthReferenceEntry(
        key="eco1989openwork",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Umberto", "Eco")],
        year="1989",
        title="The Open Work",
        publisher="Harvard University Press",
        address="Cambridge, MA",
        note="Original work published 1962",
        field_of_study="literary theory",
    ),
    SynthReferenceEntry(
        key="otto1958idea",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Rudolf", "Otto")],
        year="1958",
        title="The Idea of the Holy",
        publisher="Oxford University Press",
        address="New York, NY",
        note="Original work published 1917",
        field_of_study="philosophy of religion",
    ),
    SynthReferenceEntry(
        key="schleiermacher1988onreligion",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Friedrich", "Schleiermacher")],
        year="1988",
        title="On Religion: Speeches to Its Cultured Despisers",
        publisher="Cambridge University Press",
        address="Cambridge",
        note="Original work published 1799",
        field_of_study="theology",
    ),
    SynthReferenceEntry(
        key="aquinas1981summa",
        entry_type="book",
        broad_field="humanities_theology",
        authors=[Author("Thomas", "Aquinas")],
        year="1981",
        title="Summa Theologica",
        publisher="Christian Classics",
        address="Westminster, MD",
        note="Written c. 1265-1274",
        field_of_study="theology",
    ),
]

_MEDICINE_LIFE_SCIENCES: list[SynthReferenceEntry] = [
    SynthReferenceEntry(
        key="dollhill1950smoking",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Richard", "Doll"), Author("A. Bradford", "Hill")],
        year="1950",
        title="Smoking and carcinoma of the lung",
        journal="British Medical Journal",
        volume="2",
        number="4682",
        pages="739--748",
        doi="10.1136/bmj.2.4682.739",
        field_of_study="medicine",
    ),
    SynthReferenceEntry(
        key="watsoncrick1953molecular",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("James D.", "Watson"), Author("Francis H. C.", "Crick")],
        year="1953",
        title="Molecular structure of nucleic acids: A structure for deoxyribose nucleic acid",
        journal="Nature",
        volume="171",
        number="4356",
        pages="737--738",
        doi="10.1038/171737a0",
        field_of_study="molecular biology",
    ),
    SynthReferenceEntry(
        key="yusuf2004interheart",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Salim", "Yusuf"), Author("Steven", "Hawken"), Author("Stephanie", "Ounpuu")],
        year="2004",
        title="Effect of potentially modifiable risk factors associated with myocardial infarction in 52 countries (the INTERHEART study): Case-control study",
        journal="The Lancet",
        volume="364",
        number="9438",
        pages="937--952",
        doi="10.1016/S0140-6736(04)17018-9",
        field_of_study="epidemiology",
    ),
    SynthReferenceEntry(
        key="mckhann1984clinical",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Guy", "McKhann"), Author("David", "Drachman"), Author("Marshal", "Folstein")],
        year="1984",
        title="Clinical diagnosis of Alzheimer's disease",
        journal="Neurology",
        volume="34",
        number="7",
        pages="939--944",
        doi="10.1212/WNL.34.7.939",
        field_of_study="neurology",
    ),
    SynthReferenceEntry(
        key="barker1990fetal",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("David J. P.", "Barker")],
        year="1990",
        title="The fetal and infant origins of adult disease",
        journal="British Medical Journal",
        volume="301",
        number="6761",
        pages="1111",
        doi="10.1136/bmj.301.6761.1111",
        field_of_study="epidemiology",
    ),
    SynthReferenceEntry(
        key="marshallwarren1984unidentified",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Barry J.", "Marshall"), Author("J. Robin", "Warren")],
        year="1984",
        title="Unidentified curved bacilli in the stomach of patients with gastritis and peptic ulceration",
        journal="The Lancet",
        volume="323",
        number="8390",
        pages="1311--1315",
        doi="10.1016/S0140-6736(84)91816-6",
        field_of_study="microbiology",
    ),
    SynthReferenceEntry(
        key="fleming1929antibacterial",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Alexander", "Fleming")],
        year="1929",
        title="On the antibacterial action of cultures of a penicillium, with special reference to their use in the isolation of B. influenzae",
        journal="British Journal of Experimental Pathology",
        volume="10",
        number="3",
        pages="226--236",
        field_of_study="microbiology",
    ),
    SynthReferenceEntry(
        key="enders1949cultivation",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("John F.", "Enders"), Author("Thomas H.", "Weller"), Author("Frederick C.", "Robbins")],
        year="1949",
        title="Cultivation of the Lansing strain of poliomyelitis virus in cultures of various human embryonic tissues",
        journal="Science",
        volume="109",
        number="2822",
        pages="85--87",
        doi="10.1126/science.109.2822.85",
        field_of_study="virology",
    ),
    SynthReferenceEntry(
        key="dawber1951epidemiological",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Thomas R.", "Dawber"), Author("Gilcin F.", "Meadors"), Author("Felix E.", "Moore")],
        year="1951",
        title="Epidemiological approaches to heart disease: The Framingham Study",
        journal="American Journal of Public Health",
        volume="41",
        number="3",
        pages="279--286",
        field_of_study="epidemiology",
    ),
    SynthReferenceEntry(
        key="who2019report",
        entry_type="misc",
        broad_field="medicine_life_sciences",
        authors=[Author("", "{World Health Organization}")],
        year="2019",
        title="WHO report on the global tobacco epidemic, 2019",
        note="Technical report",
        field_of_study="public health",
    ),
    SynthReferenceEntry(
        key="snow1855mode",
        entry_type="book",
        broad_field="medicine_life_sciences",
        authors=[Author("John", "Snow")],
        year="1855",
        title="On the Mode of Communication of Cholera",
        publisher="John Churchill",
        address="London",
        field_of_study="epidemiology",
    ),
    SynthReferenceEntry(
        key="jenner1798inquiry",
        entry_type="book",
        broad_field="medicine_life_sciences",
        authors=[Author("Edward", "Jenner")],
        year="1798",
        title="An Inquiry into the Causes and Effects of the Variolae Vaccinae",
        publisher="Sampson Low",
        address="London",
        field_of_study="immunology",
    ),
    SynthReferenceEntry(
        key="selye1936syndrome",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Hans", "Selye")],
        year="1936",
        title="A syndrome produced by diverse nocuous agents",
        journal="Nature",
        volume="138",
        number="3479",
        pages="32",
        doi="10.1038/138032a0",
        field_of_study="physiology",
    ),
    SynthReferenceEntry(
        key="zinkernageldoherty1974restriction",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Rolf M.", "Zinkernagel"), Author("Peter C.", "Doherty")],
        year="1974",
        title="Restriction of in vitro T cell-mediated cytotoxicity in lymphocytic choriomeningitis within a syngeneic or semiallogeneic system",
        journal="Nature",
        volume="248",
        number="5450",
        pages="701--702",
        doi="10.1038/248701a0",
        field_of_study="immunology",
    ),
    SynthReferenceEntry(
        key="prusiner1982novel",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Stanley B.", "Prusiner")],
        year="1982",
        title="Novel proteinaceous infectious particles cause scrapie",
        journal="Science",
        volume="216",
        number="4542",
        pages="136--144",
        doi="10.1126/science.6801762",
        field_of_study="neurology",
    ),
    SynthReferenceEntry(
        key="blalocktaussig1945surgical",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Alfred", "Blalock"), Author("Helen B.", "Taussig")],
        year="1945",
        title="The surgical treatment of malformations of the heart in which there is pulmonary stenosis or pulmonary atresia",
        journal="JAMA",
        volume="128",
        number="3",
        pages="189--202",
        doi="10.1001/jama.1945.02860200029009",
        field_of_study="cardiology",
    ),
    SynthReferenceEntry(
        key="farber1948temporary",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[
            Author("Sidney", "Farber"), Author("Louis K.", "Diamond"), Author("Robert D.", "Mercer"),
        ],
        year="1948",
        title="Temporary remissions in acute leukemia in children produced by folic acid antagonist, 4-aminopteroyl-glutamic acid (aminopterin)",
        journal="New England Journal of Medicine",
        volume="238",
        number="23",
        pages="787--793",
        doi="10.1056/NEJM194806032382301",
        field_of_study="oncology",
    ),
    SynthReferenceEntry(
        key="osler1892principles",
        entry_type="book",
        broad_field="medicine_life_sciences",
        authors=[Author("William", "Osler")],
        year="1892",
        title="The Principles and Practice of Medicine",
        publisher="D. Appleton and Company",
        address="New York, NY",
        field_of_study="internal medicine",
    ),
    SynthReferenceEntry(
        key="bantingbest1922internal",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Frederick G.", "Banting"), Author("Charles H.", "Best")],
        year="1922",
        title="The internal secretion of the pancreas",
        journal="Journal of Laboratory and Clinical Medicine",
        volume="7",
        number="5",
        pages="251--266",
        field_of_study="endocrinology",
    ),
    SynthReferenceEntry(
        key="reed1900etiology",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[
            Author("Walter", "Reed"), Author("James", "Carroll"),
            Author("Aristides", "Agramonte"), Author("Jesse W.", "Lazear"),
        ],
        year="1900",
        title="The etiology of yellow fever: A preliminary note",
        journal="Public Health Papers and Reports",
        volume="26",
        pages="37--53",
        field_of_study="virology",
    ),
    SynthReferenceEntry(
        key="papanicolaoutraut1941diagnostic",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("George N.", "Papanicolaou"), Author("Herbert F.", "Traut")],
        year="1941",
        title="The diagnostic value of vaginal smears in carcinoma of the uterus",
        journal="American Journal of Obstetrics and Gynecology",
        volume="42",
        number="2",
        pages="193--206",
        field_of_study="oncology",
    ),
    SynthReferenceEntry(
        key="barnard1967operation",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Christiaan N.", "Barnard")],
        year="1967",
        title="The operation: A human cardiac transplant",
        journal="South African Medical Journal",
        volume="41",
        number="48",
        pages="1271--1274",
        field_of_study="cardiology",
    ),
    SynthReferenceEntry(
        key="mullis1990unusual",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Kary B.", "Mullis")],
        year="1990",
        title="The unusual origin of the polymerase chain reaction",
        journal="Scientific American",
        volume="262",
        number="4",
        pages="56--65",
        field_of_study="molecular biology",
    ),
    SynthReferenceEntry(
        key="lister1867antiseptic",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Joseph", "Lister")],
        year="1867",
        title="On the antiseptic principle in the practice of surgery",
        journal="The Lancet",
        volume="90",
        number="2299",
        pages="353--356",
        field_of_study="surgery",
    ),
    SynthReferenceEntry(
        key="gregg1941congenital",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Norman M.", "Gregg")],
        year="1941",
        title="Congenital cataract following German measles in the mother",
        journal="Transactions of the Ophthalmological Society of Australia",
        volume="3",
        pages="35--46",
        field_of_study="ophthalmology",
    ),
    SynthReferenceEntry(
        key="cushing1932basophil",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Harvey", "Cushing")],
        year="1932",
        title="The basophil adenomas of the pituitary body and their clinical manifestations",
        journal="Bulletin of the Johns Hopkins Hospital",
        volume="50",
        pages="137--195",
        field_of_study="endocrinology",
    ),
    SynthReferenceEntry(
        key="salk1955studies",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Jonas E.", "Salk")],
        year="1955",
        title="Studies in human subjects on active immunization against poliomyelitis",
        journal="American Journal of Public Health",
        volume="45",
        number="5",
        pages="563--591",
        field_of_study="virology",
    ),
    SynthReferenceEntry(
        key="koch1882aetiologie",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Robert", "Koch")],
        year="1882",
        title="Die Ätiologie der Tuberculose",
        journal="Berliner Klinische Wochenschrift",
        volume="19",
        pages="221--230",
        field_of_study="microbiology",
    ),
    SynthReferenceEntry(
        key="rontgen1895ueber",
        entry_type="article",
        broad_field="medicine_life_sciences",
        authors=[Author("Wilhelm C.", "Röntgen")],
        year="1895",
        title="Über eine neue Art von Strahlen",
        journal="Sitzungsberichte der Würzburger Physikalisch-Medicinischen Gesellschaft",
        pages="132--141",
        field_of_study="radiology",
    ),
    SynthReferenceEntry(
        key="harvey1628exercitatio",
        entry_type="book",
        broad_field="medicine_life_sciences",
        authors=[Author("William", "Harvey")],
        year="1628",
        title="Exercitatio Anatomica de Motu Cordis et Sanguinis in Animalibus",
        publisher="William Fitzer",
        address="Frankfurt",
        field_of_study="anatomy",
    ),
]

_CS_ENGINEERING: list[SynthReferenceEntry] = [
    SynthReferenceEntry(
        key="shannon1948mathematical",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Claude E.", "Shannon")],
        year="1948",
        title="A mathematical theory of communication",
        journal="Bell System Technical Journal",
        volume="27",
        number="3",
        pages="379--423",
        doi="10.1002/j.1538-7305.1948.tb01338.x",
        field_of_study="information theory",
    ),
    SynthReferenceEntry(
        key="vaswani2017attention",
        entry_type="inproceedings",
        broad_field="cs_engineering",
        authors=[
            Author("Ashish", "Vaswani"), Author("Noam", "Shazeer"), Author("Niki", "Parmar"),
            Author("Jakob", "Uszkoreit"), Author("Llion", "Jones"), Author("Aidan N.", "Gomez"),
            Author("Lukasz", "Kaiser"), Author("Illia", "Polosukhin"),
        ],
        year="2017",
        title="Attention is all you need",
        booktitle="Advances in Neural Information Processing Systems",
        volume="30",
        doi="10.48550/arXiv.1706.03762",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="rcoreteam2024r",
        entry_type="misc",
        broad_field="cs_engineering",
        authors=[Author("", "{R Core Team}")],
        year="2024",
        title="R: A language and environment for statistical computing",
        url="https://www.R-project.org/",
        note="Computer software",
        field_of_study="statistical computing",
    ),
    SynthReferenceEntry(
        key="turing1950computing",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Alan M.", "Turing")],
        year="1950",
        title="Computing machinery and intelligence",
        journal="Mind",
        volume="59",
        number="236",
        pages="433--460",
        doi="10.1093/mind/LIX.236.433",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="codd1970relational",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Edgar F.", "Codd")],
        year="1970",
        title="A relational model of data for large shared data banks",
        journal="Communications of the ACM",
        volume="13",
        number="6",
        pages="377--387",
        doi="10.1145/362384.362685",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="lamport1978time",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Leslie", "Lamport")],
        year="1978",
        title="Time, clocks, and the ordering of events in a distributed system",
        journal="Communications of the ACM",
        volume="21",
        number="7",
        pages="558--565",
        doi="10.1145/359545.359563",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="rivest1978method",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Ronald L.", "Rivest"), Author("Adi", "Shamir"), Author("Leonard", "Adleman")],
        year="1978",
        title="A method for obtaining digital signatures and public-key cryptosystems",
        journal="Communications of the ACM",
        volume="21",
        number="2",
        pages="120--126",
        doi="10.1145/359340.359342",
        field_of_study="cryptography",
    ),
    SynthReferenceEntry(
        key="lecun1998gradient",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Yann", "LeCun"), Author("Léon", "Bottou"), Author("Yoshua", "Bengio"), Author("Patrick", "Haffner")],
        year="1998",
        title="Gradient-based learning applied to document recognition",
        journal="Proceedings of the IEEE",
        volume="86",
        number="11",
        pages="2278--2324",
        doi="10.1109/5.726791",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="diffiehellman1976new",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Whitfield", "Diffie"), Author("Martin E.", "Hellman")],
        year="1976",
        title="New directions in cryptography",
        journal="IEEE Transactions on Information Theory",
        volume="22",
        number="6",
        pages="644--654",
        doi="10.1109/TIT.1976.1055638",
        field_of_study="cryptography",
    ),
    SynthReferenceEntry(
        key="krizhevsky2012imagenet",
        entry_type="inproceedings",
        broad_field="cs_engineering",
        authors=[Author("Alex", "Krizhevsky"), Author("Ilya", "Sutskever"), Author("Geoffrey E.", "Hinton")],
        year="2012",
        title="ImageNet classification with deep convolutional neural networks",
        booktitle="Advances in Neural Information Processing Systems",
        volume="25",
        field_of_study="machine learning",
    ),
    SynthReferenceEntry(
        key="dijkstra1968goto",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Edsger W.", "Dijkstra")],
        year="1968",
        title="Go to statement considered harmful",
        journal="Communications of the ACM",
        volume="11",
        number="3",
        pages="147--148",
        doi="10.1145/362929.362947",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="knuth1968art",
        entry_type="book",
        broad_field="cs_engineering",
        authors=[Author("Donald E.", "Knuth")],
        year="1968",
        title="The Art of Computer Programming, Volume 1: Fundamental Algorithms",
        publisher="Addison-Wesley",
        address="Reading, MA",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="church1936unsolvable",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Alonzo", "Church")],
        year="1936",
        title="An unsolvable problem of elementary number theory",
        journal="American Journal of Mathematics",
        volume="58",
        number="2",
        pages="345--363",
        doi="10.2307/2371045",
        field_of_study="theoretical computer science",
    ),
    SynthReferenceEntry(
        key="vonneumann1945firstdraft",
        entry_type="misc",
        broad_field="cs_engineering",
        authors=[Author("John", "von Neumann")],
        year="1945",
        title="First Draft of a Report on the EDVAC",
        note="Technical report, Moore School of Electrical Engineering, University of Pennsylvania",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="bernerslee1994worldwideweb",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[
            Author("Tim", "Berners-Lee"), Author("Robert", "Cailliau"), Author("Ari", "Luotonen"),
            Author("Henrik Frystyk", "Nielsen"), Author("Arthur", "Secret"),
        ],
        year="1994",
        title="The World-Wide Web",
        journal="Communications of the ACM",
        volume="37",
        number="8",
        pages="76--82",
        doi="10.1145/179606.179671",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="cerfkahn1974protocol",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Vinton G.", "Cerf"), Author("Robert E.", "Kahn")],
        year="1974",
        title="A protocol for packet network intercommunication",
        journal="IEEE Transactions on Communications",
        volume="22",
        number="5",
        pages="637--648",
        doi="10.1109/TCOM.1974.1092259",
        field_of_study="computer networking",
    ),
    SynthReferenceEntry(
        key="metropolis1953equation",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[
            Author("Nicholas", "Metropolis"), Author("Arianna W.", "Rosenbluth"),
            Author("Marshall N.", "Rosenbluth"), Author("Augusta H.", "Teller"), Author("Edward", "Teller"),
        ],
        year="1953",
        title="Equation of state calculations by fast computing machines",
        journal="The Journal of Chemical Physics",
        volume="21",
        number="6",
        pages="1087--1092",
        doi="10.1063/1.1699114",
        field_of_study="computational physics",
    ),
    SynthReferenceEntry(
        key="hopcrofttarjan1973efficient",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("John E.", "Hopcroft"), Author("Robert E.", "Tarjan")],
        year="1973",
        title="Efficient algorithms for graph manipulation",
        journal="Communications of the ACM",
        volume="16",
        number="6",
        pages="372--378",
        doi="10.1145/362248.362272",
        field_of_study="theoretical computer science",
    ),
    SynthReferenceEntry(
        key="cormen2009introduction",
        entry_type="book",
        broad_field="cs_engineering",
        authors=[
            Author("Thomas H.", "Cormen"), Author("Charles E.", "Leiserson"),
            Author("Ronald L.", "Rivest"), Author("Clifford", "Stein"),
        ],
        year="2009",
        title="Introduction to Algorithms",
        publisher="MIT Press",
        address="Cambridge, MA",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="hopper1952education",
        entry_type="inproceedings",
        broad_field="cs_engineering",
        authors=[Author("Grace M.", "Hopper")],
        year="1952",
        title="The education of a computer",
        booktitle="Proceedings of the 1952 ACM National Meeting",
        pages="243--249",
        field_of_study="computer science",
    ),
    SynthReferenceEntry(
        key="engelbart1968research",
        entry_type="inproceedings",
        broad_field="cs_engineering",
        authors=[Author("Douglas C.", "Engelbart")],
        year="1968",
        title="A research center for augmenting human intellect",
        booktitle="AFIPS Fall Joint Computer Conference",
        pages="395--410",
        field_of_study="human-computer interaction",
    ),
    SynthReferenceEntry(
        key="ritchiethompson1974unix",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Dennis M.", "Ritchie"), Author("Ken", "Thompson")],
        year="1974",
        title="The UNIX time-sharing system",
        journal="Communications of the ACM",
        volume="17",
        number="7",
        pages="365--375",
        doi="10.1145/361011.361061",
        field_of_study="operating systems",
    ),
    SynthReferenceEntry(
        key="backus1978can",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("John", "Backus")],
        year="1978",
        title="Can programming be liberated from the von Neumann style? A functional style and its algebra of programs",
        journal="Communications of the ACM",
        volume="21",
        number="8",
        pages="613--641",
        doi="10.1145/359576.359579",
        field_of_study="programming languages",
    ),
    SynthReferenceEntry(
        key="mccarthy1960recursive",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("John", "McCarthy")],
        year="1960",
        title="Recursive functions of symbolic expressions and their computation by machine, Part I",
        journal="Communications of the ACM",
        volume="3",
        number="4",
        pages="184--195",
        doi="10.1145/367177.367199",
        field_of_study="programming languages",
    ),
    SynthReferenceEntry(
        key="minskypapert1969perceptrons",
        entry_type="book",
        broad_field="cs_engineering",
        authors=[Author("Marvin", "Minsky"), Author("Seymour", "Papert")],
        year="1969",
        title="Perceptrons: An Introduction to Computational Geometry",
        publisher="MIT Press",
        address="Cambridge, MA",
        field_of_study="machine learning",
    ),
    SynthReferenceEntry(
        key="rumelhart1986learning",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[
            Author("David E.", "Rumelhart"), Author("Geoffrey E.", "Hinton"), Author("Ronald J.", "Williams"),
        ],
        year="1986",
        title="Learning representations by back-propagating errors",
        journal="Nature",
        volume="323",
        number="6088",
        pages="533--536",
        doi="10.1038/323533a0",
        field_of_study="machine learning",
    ),
    SynthReferenceEntry(
        key="hochreiterschmidhuber1997long",
        entry_type="article",
        broad_field="cs_engineering",
        authors=[Author("Sepp", "Hochreiter"), Author("Jürgen", "Schmidhuber")],
        year="1997",
        title="Long short-term memory",
        journal="Neural Computation",
        volume="9",
        number="8",
        pages="1735--1780",
        doi="10.1162/neco.1997.9.8.1735",
        field_of_study="machine learning",
    ),
    SynthReferenceEntry(
        key="goodfellow2014generative",
        entry_type="inproceedings",
        broad_field="cs_engineering",
        authors=[
            Author("Ian J.", "Goodfellow"), Author("Jean", "Pouget-Abadie"), Author("Mehdi", "Mirza"),
            Author("Bing", "Xu"), Author("David", "Warde-Farley"), Author("Sherjil", "Ozair"),
            Author("Aaron", "Courville"), Author("Yoshua", "Bengio"),
        ],
        year="2014",
        title="Generative adversarial networks",
        booktitle="Advances in Neural Information Processing Systems",
        volume="27",
        doi="10.48550/arXiv.1406.2661",
        field_of_study="machine learning",
    ),
    SynthReferenceEntry(
        key="pagebrin1999pagerank",
        entry_type="misc",
        broad_field="cs_engineering",
        authors=[
            Author("Lawrence", "Page"), Author("Sergey", "Brin"),
            Author("Rajeev", "Motwani"), Author("Terry", "Winograd"),
        ],
        year="1999",
        title="The PageRank citation ranking: Bringing order to the web",
        note="Technical report, Stanford InfoLab",
        field_of_study="information retrieval",
    ),
    SynthReferenceEntry(
        key="tanenbaum1981computer",
        entry_type="book",
        broad_field="cs_engineering",
        authors=[Author("Andrew S.", "Tanenbaum")],
        year="1981",
        title="Computer Networks",
        publisher="Prentice-Hall",
        address="Englewood Cliffs, NJ",
        field_of_study="computer networking",
    ),
]

_OTHER: list[SynthReferenceEntry] = [
    SynthReferenceEntry(
        key="higgs1964broken",
        entry_type="article",
        broad_field="other",
        authors=[Author("Peter W.", "Higgs")],
        year="1964",
        title="Broken symmetries and the masses of gauge bosons",
        journal="Physical Review Letters",
        volume="13",
        number="16",
        pages="508--509",
        doi="10.1103/PhysRevLett.13.508",
        field_of_study="physics",
    ),
]

CURATED_ENTRIES: list[SynthReferenceEntry] = (
    _SOCIAL_BEHAVIORAL + _HUMANITIES_THEOLOGY + _MEDICINE_LIFE_SCIENCES + _CS_ENGINEERING + _OTHER
)

BROAD_FIELDS: list[str] = ["social_behavioral", "humanities_theology", "medicine_life_sciences", "cs_engineering"]
